aoi:
  path: /home/hbaier/projects/tlags_v2/data/tracts2019/PA/tl_2019_42_tract_wi.shp
catalog:
  sensor: mpc_sentinel2
  start_date: '2016-01-01'
  end_date: '2016-03-31'
  cloud_cover_max: 90
  mask_clouds: false
  bands:
  - B01
  - B02
  - B03
  - B04
  - B05
  - B06
  - B07
  - B08
  - B8A
  - B09
  - B11
  - B12
auth:
  mpc_api_key: null
output:
  root: /data/hbaier/new_data/tlag/pa_imagery/q1_2016_s2_allbands/
  sub_root: false
params:
  uid_column: GEOID
  label_column: wealth_ind
  dataset_name: pa_2016_q1_s2_allbands
