aoi:
  path: /home/hbaier/projects/tlags_v2/data/tracts2019/GA/tl_2019_13_tract_wi.shp
catalog:
  sensor: mpc_sentinel2
  start_date: '2018-04-01'
  end_date: '2018-06-30'
  cloud_cover_max: 30
  mask_clouds: false
  bands:
  - B01
  - B02
  - B03
  - B04
  - B05
  - B06
  - B07
  - B08
  - B8A
  - B09
  - B11
  - B12
auth:
  mpc_api_key: null
output:
  root: /data/hbaier/new_data/tlag/ga_imagery/q2_2018_s2_allbands/
  sub_root: false
params:
  uid_column: GEOID
  label_column: wealth_ind
  dataset_name: ga_2018_q2_s2_allbands
