"""
Assemble the R^2 matrix from cross-quarter validate runs generated by
pipeline_configs/generate_cross_validate_config.py: rows = the trained
model's own quarter, columns = which quarter's imagery it was evaluated
against (restricted to the model's own held-out test set in every cell --
see that script's docstring for why that's a valid, leak-free comparison).
The diagonal is each model evaluated on its own held-out test set, exactly
what 3_validation/validate.py's per-state summary already reports one
quarter at a time -- this is the same numbers, arranged as a full matrix
instead of a single quarter-by-quarter line.

Doesn't run anything itself -- reads the epoch*_valset_<prefix>_preds.csv
files sail's task: validate already wrote (see sail PR #23; each
(model quarter, imagery quarter) pair gets its own uniquely-named CSV in
the model's own ckpt_dir, which is what makes finding them by exact path
here reliable instead of needing a "hope there's only one" glob). A blank
cell in the output means that pair hasn't been validated yet -- generate
and run that config first, this script doesn't fill in the gaps.

Usage:
    python 4_analysis/build_cross_quarter_r2_matrix.py \
        --state az --variable wealth_index_sat \
        --quarters 2016Q1 2016Q2 2016Q3 2016Q4 \
        --out-dir ./out_cross_quarter/az_wealth_index_sat
"""

import argparse
import glob
import os
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import TwoSlopeNorm
from sklearn.metrics import r2_score

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pipeline_configs"))
from generate_train_config import load_registry, resolve_state_settings  # noqa: E402
from generate_validate_config import latest_existing_version  # noqa: E402
from generate_cross_validate_config import parse_imagery_quarter  # noqa: E402


def model_ckpt_dir(state, variable, year, quarter, version, registry):
    st = resolve_state_settings(state, registry)
    data_root = st["data_root_template"].format(state=state, year=year, quarter=quarter)
    data_root = data_root if data_root.endswith("/") else data_root + "/"
    output_dir = data_root + "artifacts/"
    exp_base = f"{state}_q{quarter}_{year}_{variable}"
    v = version or latest_existing_version(output_dir, exp_base)
    return os.path.join(output_dir, f"{exp_base}_{v}")


def imagery_prefix(state, variable, year, quarter, registry):
    st = resolve_state_settings(state, registry)
    base_prefix = st["base_prefix_template"].format(state=state, year=year, quarter=quarter)
    return f"{base_prefix}_{variable}"


def find_preds_csv(ckpt_dir: str, prefix: str):
    pattern = os.path.join(ckpt_dir, f"epoch*_valset_{prefix}_preds.csv")
    matches = sorted(glob.glob(pattern))
    if len(matches) == 0:
        return None
    if len(matches) > 1:
        print(f"  WARNING: {len(matches)} files match {pattern!r}, using the newest: {matches[-1]}")
    return matches[-1]


def build_matrix(state, variable, quarters, version, registry):
    labels = [f"Q{q} {y}" for y, q in quarters]
    n = len(quarters)
    r2 = pd.DataFrame(np.nan, index=labels, columns=labels)
    n_pairs = pd.DataFrame(0, index=labels, columns=labels, dtype=int)

    for i, (model_year, model_quarter) in enumerate(quarters):
        try:
            ckpt_dir = model_ckpt_dir(state, variable, model_year, model_quarter, version, registry)
        except SystemExit as e:
            print(f"[{labels[i]}] no trained model found, skipping this row entirely: {e}")
            continue

        for j, (imagery_year, imagery_quarter) in enumerate(quarters):
            prefix = imagery_prefix(state, variable, imagery_year, imagery_quarter, registry)
            csv_path = find_preds_csv(ckpt_dir, prefix)
            if csv_path is None:
                print(f"[{labels[i]} model on {labels[j]} imagery] not validated yet -- "
                      f"expected epoch*_valset_{prefix}_preds.csv under {ckpt_dir}")
                continue
            df = pd.read_csv(csv_path)
            score = r2_score(df["label"], df["pred"])
            r2.iloc[i, j] = score
            n_pairs.iloc[i, j] = len(df)
            marker = " (diagonal)" if i == j else ""
            print(f"[{labels[i]} model on {labels[j]} imagery]{marker} r2={score:.4f} n={len(df)}")

    return r2, n_pairs


def plot_matrix(r2: pd.DataFrame, state: str, variable: str, out_path: str):
    fig, ax = plt.subplots(figsize=(1.2 * len(r2.columns) + 3, 1.2 * len(r2.index) + 3))

    finite = r2.values[np.isfinite(r2.values)]
    if finite.size == 0:
        raise SystemExit("No R^2 values to plot -- run the validate jobs first.")

    # R^2 has real polarity (0 = no explanatory power, negative = worse
    # than predicting the mean) -- a diverging colormap centered at 0 is
    # the correct choice here, not a plain sequential one.
    vmin, vmax = float(finite.min()), float(finite.max())
    if vmin < 0 < vmax:
        norm = TwoSlopeNorm(vmin=vmin, vcenter=0, vmax=vmax)
    else:
        norm = None  # all on one side of zero -- let imshow autoscale

    im = ax.imshow(r2.values, cmap="RdBu", norm=norm,
                    vmin=None if norm else vmin, vmax=None if norm else vmax)

    ax.set_xticks(range(len(r2.columns)))
    ax.set_xticklabels(r2.columns, rotation=45, ha="right")
    ax.set_yticks(range(len(r2.index)))
    ax.set_yticklabels(r2.index)
    ax.set_xlabel("Evaluated on imagery from")
    ax.set_ylabel("Model trained on")
    ax.set_title(f"{state.upper()} {variable}: cross-quarter R²\n"
                 f"(diagonal = model's own held-out test set)")

    for i in range(len(r2.index)):
        for j in range(len(r2.columns)):
            val = r2.iloc[i, j]
            if np.isfinite(val):
                ax.text(j, i, f"{val:.2f}", ha="center", va="center", fontsize=9)
            else:
                ax.text(j, i, "—", ha="center", va="center", fontsize=9, color="gray")

    # Mark the diagonal so it reads as "this model's own test set" at a glance.
    for i in range(min(len(r2.index), len(r2.columns))):
        ax.add_patch(plt.Rectangle((i - 0.5, i - 0.5), 1, 1, fill=False,
                                    edgecolor="black", linewidth=2))

    fig.colorbar(im, ax=ax, label="R²")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    print(f"Wrote {out_path}")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--state", required=True)
    p.add_argument("--variable", required=True)
    p.add_argument("--quarters", required=True, nargs="+",
                    help="YYYYQN tokens used as BOTH rows and columns, e.g. 2016Q1 2016Q2 2016Q3 2016Q4")
    p.add_argument("--version", default=None,
                    help="Trained version to use for every row's model (default: latest existing, per row)")
    p.add_argument("--out-dir", default=None, help="Default: ./out_cross_quarter/<state>_<variable>")
    args = p.parse_args()

    quarters = [parse_imagery_quarter(t) for t in args.quarters]
    registry = load_registry()

    r2, n_pairs = build_matrix(args.state, args.variable, quarters, args.version, registry)

    out_dir = Path(args.out_dir or f"./out_cross_quarter/{args.state.lower()}_{args.variable}")
    out_dir.mkdir(parents=True, exist_ok=True)
    r2.to_csv(out_dir / "r2_matrix.csv")
    n_pairs.to_csv(out_dir / "n_matrix.csv")
    print(f"Wrote {out_dir / 'r2_matrix.csv'} and {out_dir / 'n_matrix.csv'}")

    plot_matrix(r2, args.state, args.variable, str(out_dir / "r2_matrix.png"))


if __name__ == "__main__":
    main()
