"""
Assemble the R^2 matrix from cross-quarter validate runs generated by
pipeline_configs/generate_cross_validate_config.py: rows = the trained
model's own quarter, columns = which quarter's imagery it was evaluated
against (restricted to the model's own held-out test set in every cell --
see that script's docstring for why that's a valid, leak-free comparison).
The diagonal is each model evaluated on its own held-out test set, exactly
what 3_validation/validate.py's per-state summary already reports one
quarter at a time -- this is the same numbers, arranged as a full matrix
instead of a single quarter-by-quarter line.

Doesn't run anything itself -- reads the epoch*_valset_<prefix>_preds.csv
files sail's task: validate already wrote (see sail PR #23; each
(model quarter, imagery quarter) pair gets its own uniquely-named CSV,
and PR #25's validator.output_subdir keeps them all in their own
ckpt_dir/cross_quarter/ subfolder, separate from that model's normal
single-quarter validate output -- see generate_cross_validate_config.py's
CROSS_QUARTER_SUBDIR, imported here rather than hardcoded a second time).
That's what makes finding them by exact path here reliable instead of
needing a "hope there's only one" glob. A blank cell in the output means
that pair hasn't been validated yet -- generate and run that config
first, this script doesn't fill in the gaps.

Usage:
    python 4_analysis/build_cross_quarter_r2_matrix.py \
        --state az --variable wealth_index_sat \
        --quarters 2016Q1 2016Q2 2016Q3 2016Q4 \
        --out-dir ./out_cross_quarter/az_wealth_index_sat

    # Also bootstrap each cell's R^2 (1000 resamples of that cell's own
    # preds CSV, with replacement) to put a CI around it -- useful here
    # specifically because a cross-quarter cell's held-out set size varies
    # a lot cell to cell (it's always the MODEL's own test set, but
    # different imagery quarters can have different numbers of chips
    # actually present -- see generate_cross_validate_config.py), so two
    # cells' point-estimate R^2 aren't automatically comparable without
    # some sense of how much sampling noise each one carries:
    python 4_analysis/build_cross_quarter_r2_matrix.py \
        --state az --variable wealth_index_sat \
        --quarters 2016Q1 2016Q2 2016Q3 2016Q4 \
        --out-dir ./out_cross_quarter/az_wealth_index_sat \
        --bootstrap-iters 1000
"""

import argparse
import glob
import os
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import TwoSlopeNorm
from sklearn.metrics import r2_score

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "pipeline_configs"))
from generate_train_config import load_registry, resolve_state_settings  # noqa: E402
from generate_validate_config import latest_existing_version  # noqa: E402
from generate_cross_validate_config import parse_imagery_quarter, CROSS_QUARTER_SUBDIR  # noqa: E402


def model_ckpt_dir(state, variable, year, quarter, version, registry):
    st = resolve_state_settings(state, registry)
    data_root = st["data_root_template"].format(state=state, year=year, quarter=quarter)
    data_root = data_root if data_root.endswith("/") else data_root + "/"
    output_dir = data_root + "artifacts/"
    exp_base = f"{state}_q{quarter}_{year}_{variable}"
    v = version or latest_existing_version(output_dir, exp_base)
    return os.path.join(output_dir, f"{exp_base}_{v}")


def imagery_prefix(state, variable, year, quarter, registry):
    st = resolve_state_settings(state, registry)
    base_prefix = st["base_prefix_template"].format(state=state, year=year, quarter=quarter)
    return f"{base_prefix}_{variable}"


def find_preds_csv(ckpt_dir: str, prefix: str):
    # generate_cross_validate_config.py routes every cell it generates
    # (diagonal included) into ckpt_dir/<CROSS_QUARTER_SUBDIR>/ via
    # validator.output_subdir (sail PR #25) -- not ckpt_dir directly,
    # which is reserved for that model's own single-quarter validate
    # output (generate_validate_config.py).
    pattern = os.path.join(ckpt_dir, CROSS_QUARTER_SUBDIR, f"epoch*_valset_{prefix}_preds.csv")
    matches = sorted(glob.glob(pattern))
    if len(matches) == 0:
        return None
    if len(matches) > 1:
        print(f"  WARNING: {len(matches)} files match {pattern!r}, using the newest: {matches[-1]}")
    return matches[-1]


def bootstrap_r2(labels: np.ndarray, preds: np.ndarray, n_iters: int, ci: float, seed: int):
    """Non-parametric bootstrap CI for one cell's R^2.

    There's only one held-out set per cell, so there's no natural repeated
    trial to get a spread from -- this resamples (label, pred) ROW PAIRS
    together, with replacement, n_iters times and re-scores each resample,
    giving the sampling-noise band you'd otherwise have no way to put on a
    single point-estimate R^2. Standard percentile-bootstrap CI (no
    normality assumption on the R^2 statistic, which isn't symmetric).
    """
    rng = np.random.default_rng(seed)
    n = len(labels)
    scores = np.full(n_iters, np.nan)
    for b in range(n_iters):
        idx = rng.integers(0, n, size=n)
        y_true, y_pred = labels[idx], preds[idx]
        if np.ptp(y_true) == 0:
            # Every resampled label identical -> zero total variance to
            # explain -> R^2 undefined. Only realistic for a very small
            # held-out set; skip this draw rather than let sklearn's
            # edge-case return value quietly skew the distribution.
            continue
        scores[b] = r2_score(y_true, y_pred)

    valid = scores[~np.isnan(scores)]
    if valid.size == 0:
        return None
    alpha = (1 - ci) / 2
    lo, hi = np.percentile(valid, [100 * alpha, 100 * (1 - alpha)])
    return {
        "r2_boot_mean": float(valid.mean()),
        "r2_boot_std": float(valid.std(ddof=1)) if valid.size > 1 else 0.0,
        "ci_lower": float(lo),
        "ci_upper": float(hi),
        "n_boot": int(valid.size),
    }


def build_matrix(state, variable, quarters, version, registry,
                  bootstrap_iters=0, ci=0.95, seed=1337):
    labels = [f"Q{q} {y}" for y, q in quarters]
    n = len(quarters)
    r2 = pd.DataFrame(np.nan, index=labels, columns=labels)
    n_pairs = pd.DataFrame(0, index=labels, columns=labels, dtype=int)
    bootstrap_rows = []

    for i, (model_year, model_quarter) in enumerate(quarters):
        try:
            ckpt_dir = model_ckpt_dir(state, variable, model_year, model_quarter, version, registry)
        except SystemExit as e:
            print(f"[{labels[i]}] no trained model found, skipping this row entirely: {e}")
            continue

        for j, (imagery_year, imagery_quarter) in enumerate(quarters):
            prefix = imagery_prefix(state, variable, imagery_year, imagery_quarter, registry)
            csv_path = find_preds_csv(ckpt_dir, prefix)
            if csv_path is None:
                print(f"[{labels[i]} model on {labels[j]} imagery] not validated yet -- "
                      f"expected epoch*_valset_{prefix}_preds.csv under {ckpt_dir}")
                continue
            df = pd.read_csv(csv_path)
            y_true = df["label"].to_numpy()
            y_pred = df["pred"].to_numpy()
            score = r2_score(y_true, y_pred)
            r2.iloc[i, j] = score
            n_pairs.iloc[i, j] = len(df)
            marker = " (diagonal)" if i == j else ""

            boot_msg = ""
            if bootstrap_iters > 0:
                boot = bootstrap_r2(y_true, y_pred, bootstrap_iters, ci, seed)
                if boot is None:
                    print(f"  WARNING: every bootstrap resample for {labels[i]} model on "
                          f"{labels[j]} imagery had zero label variance -- skipping CI for this cell")
                else:
                    bootstrap_rows.append({
                        "model_quarter": labels[i], "imagery_quarter": labels[j],
                        "r2": score, "n": len(df), **boot,
                    })
                    boot_msg = (f"  {int(ci * 100)}% CI=[{boot['ci_lower']:.4f}, "
                                f"{boot['ci_upper']:.4f}] (n_boot={boot['n_boot']})")

            print(f"[{labels[i]} model on {labels[j]} imagery]{marker} r2={score:.4f} n={len(df)}{boot_msg}")

    bootstrap_df = pd.DataFrame(bootstrap_rows)
    return r2, n_pairs, bootstrap_df


def plot_matrix(r2: pd.DataFrame, state: str, variable: str, out_path: str):
    fig, ax = plt.subplots(figsize=(1.2 * len(r2.columns) + 3, 1.2 * len(r2.index) + 3))

    finite = r2.values[np.isfinite(r2.values)]
    if finite.size == 0:
        raise SystemExit("No R^2 values to plot -- run the validate jobs first.")

    # R^2 has real polarity (0 = no explanatory power, negative = worse
    # than predicting the mean) -- a diverging colormap centered at 0 is
    # the correct choice here, not a plain sequential one.
    vmin, vmax = float(finite.min()), float(finite.max())
    if vmin < 0 < vmax:
        norm = TwoSlopeNorm(vmin=vmin, vcenter=0, vmax=vmax)
    else:
        norm = None  # all on one side of zero -- let imshow autoscale

    im = ax.imshow(r2.values, cmap="RdBu", norm=norm,
                    vmin=None if norm else vmin, vmax=None if norm else vmax)

    ax.set_xticks(range(len(r2.columns)))
    ax.set_xticklabels(r2.columns, rotation=45, ha="right")
    ax.set_yticks(range(len(r2.index)))
    ax.set_yticklabels(r2.index)
    ax.set_xlabel("Evaluated on imagery from")
    ax.set_ylabel("Model trained on")
    ax.set_title(f"{state.upper()} {variable}: cross-quarter R²\n"
                 f"(diagonal = model's own held-out test set)")

    for i in range(len(r2.index)):
        for j in range(len(r2.columns)):
            val = r2.iloc[i, j]
            if np.isfinite(val):
                ax.text(j, i, f"{val:.2f}", ha="center", va="center", fontsize=9)
            else:
                ax.text(j, i, "—", ha="center", va="center", fontsize=9, color="gray")

    # Mark the diagonal so it reads as "this model's own test set" at a glance.
    for i in range(min(len(r2.index), len(r2.columns))):
        ax.add_patch(plt.Rectangle((i - 0.5, i - 0.5), 1, 1, fill=False,
                                    edgecolor="black", linewidth=2))

    fig.colorbar(im, ax=ax, label="R²")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    print(f"Wrote {out_path}")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--state", required=True)
    p.add_argument("--variable", required=True)
    p.add_argument("--quarters", required=True, nargs="+",
                    help="YYYYQN tokens used as BOTH rows and columns, e.g. 2016Q1 2016Q2 2016Q3 2016Q4")
    p.add_argument("--version", default=None,
                    help="Trained version to use for every row's model (default: latest existing, per row)")
    p.add_argument("--out-dir", default=None, help="Default: ./out_cross_quarter/<state>_<variable>")
    p.add_argument("--bootstrap-iters", type=int, default=0,
                    help="Bootstrap resamples per cell for a CI around that cell's R^2 "
                         "(default 0: skip bootstrapping entirely). Each cell's own preds "
                         "CSV is resampled independently, after it's already been read for "
                         "the point estimate -- no extra inference, no re-running the model.")
    p.add_argument("--ci", type=float, default=0.95, help="Bootstrap CI width (default 0.95)")
    p.add_argument("--seed", type=int, default=1337, help="Bootstrap RNG seed")
    args = p.parse_args()

    quarters = [parse_imagery_quarter(t) for t in args.quarters]
    registry = load_registry()

    r2, n_pairs, bootstrap_df = build_matrix(
        args.state, args.variable, quarters, args.version, registry,
        bootstrap_iters=args.bootstrap_iters, ci=args.ci, seed=args.seed,
    )

    out_dir = Path(args.out_dir or f"./out_cross_quarter/{args.state.lower()}_{args.variable}")
    out_dir.mkdir(parents=True, exist_ok=True)
    r2.to_csv(out_dir / "r2_matrix.csv")
    n_pairs.to_csv(out_dir / "n_matrix.csv")
    print(f"Wrote {out_dir / 'r2_matrix.csv'} and {out_dir / 'n_matrix.csv'}")

    if args.bootstrap_iters > 0:
        boot_path = out_dir / "r2_bootstrap.csv"
        bootstrap_df.to_csv(boot_path, index=False)
        print(f"Wrote {boot_path} ({len(bootstrap_df)} cell(s), {args.bootstrap_iters} "
              f"iters/cell, {int(args.ci * 100)}% CI)")

    plot_matrix(r2, args.state, args.variable, str(out_dir / "r2_matrix.png"))


if __name__ == "__main__":
    main()
